### ISSUE TITLE
Citation formatting fails when running as a container

### ISSUE THREAD

**Issue by rdmpage** [rdmpage/refindit#2]
When running as a container and user tries to format a citation we get this error:

> RangeError:
> The normalization form should be one of NFC, NFD, NFKC, NFKD. at String.normalize (native) at Object.id (/usr/src/app/format/node_modules/jsdom/lib/jsdom/level2/html.js:179:22) at lastChance (/usr/src/app/format/node_modules/jsdom/lib/jsdom/level2/core.js:515:11) at visit (/usr/src/app/format/node_modules/jsdom/lib/jsdom/level1/core.js:64:9) at Object.visitTree (/usr/src/app/format/node_modules/jsdom/lib/jsdom/level1/core.js:76:5) at Object.core.Document.importNode (/usr/src/app/format/node_modules/jsdom/lib/jsdom/level2/core.js:553:10) at CSL_NODEJS_JSDOM.importNode (/usr/src/app/format/csl_nodejs_jsdom.js:315:27) at CSL_NODEJS_JSDOM.addInstitutionNodes (/usr/src/app/format/csl_nodejs_jsdom.js:663:35) at new CSL.Engine (/usr/src/app/format/citeprocmodule.js:1990:18) at new citeprocnode.createEngine (/usr/src/app/format/citeprocnode.js:13:20)
>

**Comment by rdmpage** [comment]
See https://github.com/tmpvar/jsdom/commit/1b342a1c7fcd250c1fc2f991cb06177374ff302d for possible clues

**Comment by rdmpage** [comment]
Fixed by 6f2981bb8720e6a76c65dca7456ff548a3b325c4
